### ISSUE TITLE
Convert projects to PCL

### ISSUE THREAD

**Issue by matteobruni** [DotNetDevs/Synology#65]

**Comment by matteobruni** [comment]
Tried to create the main Synology PCL but some .NET references are not ready to be ported like System.ComponentModel.DataAnnotations, System.ComponentModel and System.Diagnostics.StackTrace

**Comment by matteobruni** [comment]
Use the PCL branch for the implementation.
The PCL is an hard way but a multiplatform project can be an alternative but the nuspec must be rewritten and I don't know how the dependencies works with the multiplatform solution

**Comment by matteobit** [comment]
All projects are converted to PCL but Visual Studio 2015 Update 2 gives error on the AnyCPU configuration but it create the dll and AppVeyor doesn't build.

**Comment by matteobit** [comment]
Everything works, but the nuget package must be tested with pcl and non-pcl projects
